# dataset
train_csv: '../data/crop/train_crop.csv'
val_csv: '../data/crop/val_crop.csv'
test_csv: '../data/crop/test_crop.csv'
encoder_classes_path: '../data/encoder_classes.npy'
image_size: 224
# model
model_name: 'convnext_large_384_in22ft1k'
pretrained: True
drop_rate: 0.0
embedding_size: 512
num_classes: 108
arc_s: 30.0
arc_m: 0.5
arc_easy_margin: False
arc_ls_eps: 0.0
# dataloader
batch_size: 8
num_workers: 2
# trainer
debug: False
optimizer: 'adam'
learning_rate: 3.0e-4
weight_decay: 1.0e-6
checkpoints_dir: 'checkpoints'
accumulate_grad_batches: 1
auto_lr_find: False
auto_scale_batch_size: False
fast_dev_run: False
gpus: [1]
max_epochs: 10
precision: 16
stochastic_weight_avg: True
# inference
n_neightbors: 2000
threshold: 0.5
re_conf: 0.8
